version: "3"

services:
  mysql_db:
    build:
      context: ../mysql
      dockerfile: Dockerfile
    hostname: mysql_db
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db:/docker-entrypoint-initdb.d/
    networks:
      - internal_network

  app:
    image: nicolascbv/ignite-notification-app:latest 
    environment:
      - 'DATABASE_URL=mysql://root:password@mysql_db/db'
      - 'SHADOW_DATABASE_URL=mysql://root:password@mysql_db/shadow_db'
    hostname: app
    restart: always
    ports: 
      - "3030:3030"
    networks:
      - internal_network
      - external_network
    depends_on:
      - mysql_db

volumes:
  db:
    driver: local
  shadow_db:
    driver: local

networks:
  external_network:
  internal_network:
    internal: true
